orm: active_record
orm_base: '::ApplicationRecord'
storage: :aws
dir_prefix: uploads
controller_base: '::ApplicationController'
mailer_base: '::ApplicationMailer'
mailer_layout: open_invoice/mailer
raise_in_development: true
catch_engine_errors: true
dummy_session_store: :cache_store
dummy_cache_store: :redis_cache_store
